---
abstract: 'Get fortune cookies from http://www.der-postillion.com!'
author:
  - 'Maik Hentsche <caldrin@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300024, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fortune-WWW-Postillion
version: 0.001
